### ISSUE TITLE
升级okhttp到okhttp3后导致煎蛋rxjava找不到okhttp

### ISSUE THREAD

**Issue by jp1017** [ZhaoKaiQiang/OkHttpPlus#2]
如题

as导入最新的 https://github.com/ZhaoKaiQiang/JianDanRxJava 项目，找不到okhttp包，初步认定是该库升级okhttp3导致。

**Comment by ZhaoKaiQiang** [comment]
请到jianDanRxJava提issue，已经版本修复了
